radius-spawn: 100
min-depth: 25
number-of-sponges: 100 # -1 if random
durability-level: 1
world: "world"
wipe:
  name: "Wipe"
  lore:
    - "Line 1"
    - "Line 2"
helmet:
  name: "Helmet"
  lore:
    - "Line 1"
    - "Line 2"
chestPlate:
  name: "ChestPlate"
  lore:
    - "Line 1"
    - "Line 2"
leggings:
  name: "Leggings"
  lore:
    - "Line 1"
    - "Line 2"
boots:
  name: "Boots"
  lore:
    - "Line 1"
    - "Line 2"

# Maximum millis that the thread setting the blocks should take per tick.
# Should be below 25.
MaxMillisPerTick: 12